'use client';
import {useEffect,useState,useRef} from 'react';
import {InboxLayout} from '../components/inbox-layout';
import {formatMessageDate} from '../lib/dates';
import {Inbox, Star, Search, RefreshCw, ChevronLeft, ExternalLink, Mail, Circle, CheckCheck, Terminal, X} from 'lucide-react';
type Message={id:string;subject:string;author:string;date?:string};
type Detail=Message & {body:string;date:string;thread:{id:string;text:string}[];stale:boolean};
type SenderProfile={name:string;addresses:string[];messages:Message[]};
const lists=[
 {id:'lkml',name:'Linux kernel',short:'LKML',address:'linux-kernel@vger.kernel.org',base:'https://lkml.org',index:'/lkml/last100'},
 {id:'linus',name:'Linus threads',short:'Linus threads',address:'torvalds@linux-foundation.org',base:'https://lkml.org',index:'/lkml/last100'},
 {id:'regressions',name:'Regressions',short:'Regressions',address:'regressions@lists.linux.dev',base:'https://lore.kernel.ime.usp.br',index:'/regressions/'},
 {id:'stable',name:'Stable kernel',short:'Stable kernel',address:'stable@vger.kernel.org',base:'https://lore.kernel.ime.usp.br',index:'/stable/'},
 {id:'linux-next',name:'linux-next',short:'linux-next',address:'linux-next@vger.kernel.org',base:'https://lore.kernel.ime.usp.br',index:'/linux-next/'},
 {id:'netdev',name:'Networking',short:'Networking',address:'netdev@vger.kernel.org',base:'https://lists.openwall.net',index:'/netdev/'},
 {id:'releases',name:'Releases & pulls',short:'Releases & pulls',address:'linux-kernel@vger.kernel.org',base:'https://lkml.org',index:'/lkml/last100'},
 {id:'linux-cve-announce',name:'Kernel CVEs',short:'Kernel CVEs',address:'linux-cve-announce@vger.kernel.org',base:'https://lists.openwall.net',index:'/linux-cve-announce/'},
 {id:'oss-security',name:'OSS Security',short:'OSS Security',address:'oss-security@lists.openwall.com',base:'https://www.openwall.com/lists',index:'/oss-security/'}
];
const feedGroups=[
 {id:'overview',name:'Overview',ids:['releases','linus','lkml']},
 {id:'fixes-security',name:'Fixes & security',ids:['regressions','stable','linux-cve-announce','oss-security']},
 {id:'development',name:'Development',ids:['linux-next','netdev']}
].map(group=>({...group,feeds:group.ids.map(id=>lists.find(feed=>feed.id===id)!)}));
export default function Home(){
 const [list,setList]=useState('lkml');
 const [counts,setCounts]=useState<Record<string,number>>({});
 useEffect(()=>{try{const saved=localStorage.getItem('kernel-list');if(lists.some(l=>l.id===saved))setList(saved!)}catch{}
 const controller=new AbortController();
 lists.forEach(l=>fetch('/api/messages?list='+l.id,{signal:controller.signal}).then(async r=>{if(!r.ok)return;const d=await r.json() as {messages:Message[]};let read:string[]=[];try{read=JSON.parse(localStorage.getItem('kernel-read')||'[]')}catch{}setCounts(c=>({...c,[l.id]:d.messages.filter((m:Message)=>!read.includes(m.id)).length}))}).catch(()=>{}));
 return()=>controller.abort();},[]);
 function switchList(id:string){setList(id);try{localStorage.setItem('kernel-list',id)}catch{}}
 return <Mailbox key={list} list={list} switchList={switchList} counts={counts} reportCount={(n:number)=>setCounts(c=>c[list]===n?c:{...c,[list]:n})}/>;
}
function Mailbox({list,switchList,counts,reportCount}:{list:string;switchList:(id:string)=>void;counts:Record<string,number>;reportCount:(n:number)=>void}){
 const source=lists.find(l=>l.id===list)!;
 const linus=list==='linus';
 const filtered=linus||list==='releases';
 const [latest,setLatest]=useState('');
 const mounted=useRef(true);
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false}},[]);
 const [senderName,setSenderName]=useState(''),[profile,setProfile]=useState<SenderProfile|null>(null),[profileError,setProfileError]=useState('');
 const senderDialog=useRef<HTMLDialogElement>(null);
 function openSender(name:string){setSenderName(name);senderDialog.current?.showModal()}
 useEffect(()=>{if(!senderName)return;setProfile(null);setProfileError('');const controller=new AbortController();fetch('/api/sender?list='+list+'&name='+encodeURIComponent(senderName),{signal:controller.signal}).then(async r=>{const d=await r.json() as SenderProfile & {error?:string};if(!r.ok)throw Error(d.error);return d}).then(setProfile).catch(e=>{if(e.name!=='AbortError')setProfileError(e.message)});return()=>controller.abort()},[senderName]);
 const [messages,setMessages]=useState<Message[]>([]),[selected,setSelected]=useState(''),[detail,setDetail]=useState<Detail|null>(null),[query,setQuery]=useState(''),[folder,setFolder]=useState('Inbox'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[messageError,setMessageError]=useState(''),[updated,setUpdated]=useState(''),[stale,setStale]=useState(false);
 const [read,setRead]=useState<string[]>([]),[stars,setStars]=useState<string[]>([]),[ready,setReady]=useState(false);
 useEffect(()=>{try {setRead(JSON.parse(localStorage.getItem('kernel-read')||'[]'));setStars(JSON.parse(localStorage.getItem('kernel-stars')||'[]'));}catch{} setReady(true)},[]);
 useEffect(()=>{if(ready){localStorage.setItem('kernel-read',JSON.stringify(read));localStorage.setItem('kernel-stars',JSON.stringify(stars));}},[read,stars,ready]);
 async function refresh(){setBusy(true);setError('');try{const r=await fetch('/api/messages?list='+list);const d=await r.json() as {messages:Message[];fetched:number;stale:boolean;latest?:string;error?:string};if(!r.ok)throw Error(d.error);if(!mounted.current)return;setMessages(d.messages);setUpdated(formatMessageDate(d.fetched*1000,'time'));setStale(d.stale);setLatest(d.latest||'');}catch(e){setError(e instanceof Error?e.message:'Unable to load messages.')}finally{setBusy(false)}}
 useEffect(()=>{refresh();const t=setInterval(refresh,300000);return()=>clearInterval(t)},[]);
 useEffect(()=>{async function loadTheme(){try{const r=await fetch('/api/theme');if(!r.ok)return;const d=await r.json() as {name:string;colors:Record<string,string>};Object.entries(d.colors).forEach(([k,v])=>document.documentElement.style.setProperty('--'+k,String(v)));}catch{}}loadTheme();const t=setInterval(loadTheme,30000);return()=>clearInterval(t)},[]);
 useEffect(()=>{if(!selected)return;setDetail(null);setMessageError('');const controller=new AbortController();fetch('/api/message?list='+list+'&id='+encodeURIComponent(selected),{signal:controller.signal}).then(async r=>{const d=await r.json() as Detail & {error?:string};if(!r.ok)throw Error(d.error);return d}).then(d=>{setDetail(d);if(d.date)setMessages(rows=>rows.map(m=>m.id===d.id?{...m,date:d.date}:m))}).catch(e=>{if(e.name!=='AbortError')setMessageError(e.message)});setRead(old=>old.includes(selected)?old:[...old,selected]);return()=>controller.abort()},[selected]);
 const visible=messages.filter(m=>(folder!=='Starred'||stars.includes(m.id))&&(folder!=='Unread'||!read.includes(m.id))&&(m.subject+' '+m.author).toLowerCase().includes(query.toLowerCase()));
 function toggleStar(id:string){setStars(a=>a.includes(id)?a.filter(x=>x!==id):[...a,id])}
 const unread=messages.filter(m=>!read.includes(m.id)).length;
 useEffect(()=>{if(ready&&updated)reportCount(unread)},[ready,updated,unread,reportCount]);
 return <InboxLayout reading={Boolean(selected)}>
 <aside className="sidebar"><div className="brand"><Terminal size={26}/><span>kernel<span className="brand-sub">inbox</span></span></div><div className="account"><span className="account-icon"><Mail size={19}/></span><div>{source.name}<small>{source.address}</small></div></div><div className="section-label">MAILBOX</div><nav aria-label="Mailbox">{[{name:'Inbox',icon:Inbox,count:messages.length},{name:'Unread',icon:Circle,count:unread},{name:'Starred',icon:Star,count:filtered?messages.filter(m=>stars.includes(m.id)).length:stars.filter(id=>id.startsWith('/'+list+'/')).length}].map(({name,icon:Icon,count})=><button className={'nav-item '+(folder===name?'active':'')} onClick={()=>{setFolder(name);setSelected('')}} key={name}><Icon size={17}/><span>{name}</span><small>{count}</small></button>)}</nav><div className="section-label">FEEDS</div><nav aria-label="Feeds">{feedGroups.map(group=><section className="feed-group" key={group.id} aria-labelledby={'feed-group-'+group.id}><h2 id={'feed-group-'+group.id} className="feed-group-label">{group.name}</h2>{group.feeds.map(l=><button key={l.id} className={"nav-item "+(l.id===list?"active":"")} aria-pressed={l.id===list} onClick={()=>switchList(l.id)}><Mail size={16}/><span>{l.short}</span><small aria-label="Unread messages">{counts[l.id]??"…"}</small></button>)}</section>)}</nav><div className="sidebar-note"><span className="status-dot"/>{linus?'Threads Linus posted in':list==='releases'?'Releases & pull requests':'Public mailing list'}<div>{filtered?'Past 7 days · LKML':'Up to 100 recent messages'}<br/>Checks every 5 minutes{linus&&<><br/>Matched by archive sender name</>}</div></div></aside>
 <section className="mailbox"><header className="mailbox-header"><div><h1>{folder}</h1><select className="list-switcher" aria-label="Select feed" value={list} onChange={e=>switchList(e.target.value)}>{feedGroups.map(group=><optgroup key={group.id} label={group.name}>{group.feeds.map(l=><option key={l.id} value={l.id}>{l.short}</option>)}</optgroup>)}</select></div><button className="icon-button" aria-label="Refresh messages" title="Refresh messages" onClick={refresh} disabled={busy}><RefreshCw size={18} className={busy?'spin':''}/></button></header><div className="search"><Search size={17}/><input aria-label="Search loaded messages" placeholder="Search these messages…" value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="list-toolbar"><span>{visible.length} {linus?'threads':'messages'}</span><button title="Mark loaded messages read" onClick={()=>setRead(a=>Array.from(new Set([...a,...messages.map(m=>m.id)])))}><CheckCheck size={16}/> Mark read</button></div>{error&&<div className="error" role="alert">{error}</div>}{latest&&<div className="archive-date">Archive’s latest message: {formatMessageDate(latest,'day')}</div>}{stale&&<div className="error">Archive unavailable · showing cached mail</div>}<div className="message-list" aria-label="Messages">{visible.map(m=><div className={'message-row '+(selected===m.id?'selected ':'')+(!read.includes(m.id)?'unread':'')} key={m.id}><div className="row-top"><button className="sender-link" onClick={()=>openSender(m.author)} title="View sender details">{m.author}</button><time title={m.date?formatMessageDate(m.date):'Archive date; open message for full timestamp'}>{m.date?formatMessageDate(m.date,'day'):m.id.split('/').slice(3,5).join('/')}</time></div><button className="message-select" onClick={()=>setSelected(m.id)}><div className="subject">{m.subject}</div><div className="message-kind">{m.subject.toLowerCase().includes('[patch')?'PATCH DISCUSSION':list==='linux-cve-announce'?'CVE ANNOUNCEMENT':list==='oss-security'?'SECURITY DISCUSSION':'KERNEL DISCUSSION'}</div></button><button className={'star-button '+(stars.includes(m.id)?'starred':'')} aria-label={stars.includes(m.id)?'Unstar message':'Star message'} aria-pressed={stars.includes(m.id)} onClick={()=>toggleStar(m.id)}><Star size={15} fill={stars.includes(m.id)?'currentColor':'none'}/></button></div>)}{!visible.length&&<div className="empty-list">{busy?'Fetching the latest mail…':error?'Messages will appear when the archive is available.':linus?'No Linus threads found in the past 7 days.':list==='releases'?'No releases or pull requests found in the past 7 days.':'No messages here.'}</div>}</div><footer>{busy?'Checking archive…':updated?'Synced '+updated:'Waiting for archive'}<a href={source.base+source.index} target="_blank" rel="noreferrer">{new URL(source.base).hostname} <ExternalLink size={12}/></a></footer></section>
 <section className="reader"><header className="reader-toolbar"><button className="back" onClick={()=>setSelected('')}><ChevronLeft size={17}/> Mailbox</button><span>{source.short}</span>{selected&&<div><button className="icon-button" aria-label="Star selected message" aria-pressed={stars.includes(selected)} onClick={()=>toggleStar(selected)}><Star size={17} fill={stars.includes(selected)?'currentColor':'none'}/></button><a href={source.base+selected} target="_blank" rel="noreferrer">View original <ExternalLink size={15}/></a></div>}</header>{!selected?<div className="welcome"><div className="welcome-icon"><Inbox size={36} strokeWidth={1.2}/></div><h2>{list==='lkml'?'A window into the kernel.':source.name}</h2><p>{linus?'Threads with posts from Linus Torvalds in the past 7 days. Select one to read his message and follow the conversation.':list==='releases'?'Kernel release announcements and pull requests from the past 7 days.':'Select a message to read the conversation.'}</p><span>{source.short} · LOCAL READER</span></div>:messageError?<div className="empty-list" role="alert">{messageError}<p><a href={source.base+selected} target="_blank" rel="noreferrer">Read in archive ↗</a></p></div>:!detail?<div className="empty-list" role="status">Opening message…</div>:<div className="message-content" key={selected} tabIndex={0} aria-label="Message and conversation"><div className="message-heading"><div className="eyebrow">{detail.subject.toLowerCase().includes('[patch')?'PATCH DISCUSSION':'MAILING LIST'}</div><h2>{detail.subject}</h2><div className="sender"><span className="avatar">{detail.author.match(/[\p{L}\p{N}]/u)?.[0].toLocaleUpperCase()||'?'}</span><div><button className="sender-link" onClick={()=>openSender(detail.author)} title="View sender details">{detail.author.replace(/\s*<>$/,'')}</button><small>to {(source.id==='lkml'||filtered)?'linux-kernel':source.id}</small></div></div><div className="message-date">{formatMessageDate(detail.date)}</div>{detail.stale&&<p className="muted">Saved copy · archive currently unavailable</p>}</div><pre className="body">{detail.body.split('\n').map((line,i)=><span key={i} className={line.startsWith('>')?'quote':line.startsWith('+')?'added':line.startsWith('-')?'removed':line.startsWith('@@')?'hunk':''}>{line}{'\n'}</span>)}</pre>{detail.thread.length>0&&<div className="thread"><h3>In this conversation</h3>{detail.thread.map(t=><button key={t.id} onClick={()=>setSelected(t.id)}><Mail size={15}/>{t.text}<span>→</span></button>)}</div>}</div>}</section>
 <dialog className="sender-dialog" ref={senderDialog} aria-labelledby="sender-title" onClose={()=>setSenderName('')} onClick={e=>{if(e.target===e.currentTarget)senderDialog.current?.close()}}><div className="profile-header"><div><div className="eyebrow">SENDER</div><h2 id="sender-title">{profile?.name||senderName.replace(/\s*<.*>$/,'')}</h2></div><button className="icon-button" aria-label="Close sender details" onClick={()=>senderDialog.current?.close()}><X size={20}/></button></div><div className="profile-content">{profileError?<p role="alert">{profileError}</p>:!profile?<p role="status">Loading sender details…</p>:<><div className="profile-info">{profile.addresses.length?profile.addresses.map(a=><p key={a}>{a}</p>):<p>Email address not provided by this archive.</p>}<p>Posts to {source.name}.</p></div><h3>Messages from this sender <span>({profile.messages.length})</span></h3><p className="profile-scope">From the latest inbox and messages saved on this computer. Matched by sender name; this is not their complete posting history.</p><div className="profile-messages">{profile.messages.map(m=><button key={m.id} onClick={()=>{setSelected(m.id);senderDialog.current?.close()}}><Mail size={16}/><span>{m.subject}</span><span>→</span></button>)}{!profile.messages.length&&<p>No saved messages from this sender yet.</p>}</div></>}</div></dialog>
 </InboxLayout>
}
